### ISSUE TITLE
add "call evaluted" tick or cross next to call on evaluate page

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#271]
On evaluate page that lists the calls to evaluate, display a tick or cross next to each call when all calls have been evaluated. 

The logic could be: 
- when all eligible proposals have had their evaluations completed and closed?

**Comment by cpina** [comment]
Should we also have a "Proposal evaluated"? now it can be done implicitly by "Evaluation Date". If SPI wants to write drafts and then "confirm that is finished" it might make sense.

**Comment by cpina** [comment]
Instead of having a "cross" next to the call I've started implementing a "close_evaluation" button (next to each call in http://127.0.0.1:8000/logged/evaluation/list/). This will allow us to explain why a call cannot be closed (missing evaluation, incomplete evaluations, etc.). E.g.: http://127.0.0.1:8000/logged/call-evaluation/2/close_evaluation/
